# Generated by Django 5.2.1 on 2025-05-28 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=100, verbose_name='Spécialité')),
                ('numero_ordre', models.CharField(max_length=50, verbose_name="Numéro d'ordre")),
                ('annees_experience', models.PositiveIntegerField(verbose_name="Années d'expérience")),
                ('nom_cabinet', models.CharField(max_length=150, verbose_name='Nom du cabinet')),
                ('adresse_cabinet', models.TextField(verbose_name='Adresse du cabinet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone du cabinet')),
                ('telephone_urgence', models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone d'urgence")),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
