# Generated by Django 5.2.1 on 2025-05-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dernier_rdv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='frequence',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='nom',
            field=models.CharField(default='2000-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pathologie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='poids',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='prenom',
            field=models.CharField(default='Nom inconnu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='prochain_rdv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('stable', 'Stable'), ('surveillance', 'Surveillance'), ('critique', 'Critique')], default='stable', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='tension',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='urgence',
            field=models.BooleanField(default=False),
        ),
    ]
