# Generated by Django 5.2.1 on 2025-05-26 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_adresse_patient_dernier_rdv_patient_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('stable', 'Stable'), ('surveillance', 'Surveillance'), ('critique', 'Critique'), ('urgence', 'urgence')], default='stable', max_length=20),
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField()),
                ('heure', models.TimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
