# Generated by Django 5.2.1 on 2025-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_statut_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='motif',
            field=models.CharField(choices=[('consultation', 'Consultation générale'), ('suivi', 'Suivi médical'), ('urgence', 'Urgence'), ('vaccination', 'Vaccination'), ('bilan', 'Bilan de santé'), ('autre', 'Autre')], default='consultation', max_length=100),
        ),
    ]
